-- MySQL Script generated by MySQL Workbench
-- Thu Jan 12 16:17:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_presupuesto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_presupuesto` ;

-- -----------------------------------------------------
-- Schema db_presupuesto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_presupuesto` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_presupuesto` ;

-- -----------------------------------------------------
-- Table `db_presupuesto`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_presupuesto`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `dui` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `estado_usuario` ENUM('A', 'I') NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;

CREATE UNIQUE INDEX `uk_dui` ON `db_presupuesto`.`usuario` (`dui` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_presupuesto`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_presupuesto`.`login` (
  `id_login` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `clave` VARCHAR(500) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `estado_login` ENUM('A', 'I') NOT NULL,
  `password_token` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`id_login`),
  CONSTRAINT `pk_login_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_presupuesto`.`usuario` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;

CREATE INDEX `pk_login_usuario` ON `db_presupuesto`.`login` (`id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_presupuesto`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_presupuesto`.`cuenta` (
  `id_cuenta` INT NOT NULL AUTO_INCREMENT,
  `id_login` INT NOT NULL,
  `numero_cuenta` VARCHAR(50) NOT NULL,
  `saldo_disponible` DOUBLE(10,4) NOT NULL,
  PRIMARY KEY (`id_cuenta`),
  CONSTRAINT `pk_cuenta_login`
    FOREIGN KEY (`id_login`)
    REFERENCES `db_presupuesto`.`login` (`id_login`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;

CREATE UNIQUE INDEX `uk_numero_cuenta` ON `db_presupuesto`.`cuenta` (`numero_cuenta` ASC) VISIBLE;

CREATE INDEX `pk_cuenta_login` ON `db_presupuesto`.`cuenta` (`id_login` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_presupuesto`.`egreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_presupuesto`.`egreso` (
  `id_egreso` INT NOT NULL AUTO_INCREMENT,
  `id_cuenta` INT NOT NULL,
  `saldo_egreso` DOUBLE(6,2) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `estado_egreso` ENUM('A', 'I') NOT NULL,
  `fecha_egreso` DATE NOT NULL,
  PRIMARY KEY (`id_egreso`),
  CONSTRAINT `pk_cuenta_engreso`
    FOREIGN KEY (`id_cuenta`)
    REFERENCES `db_presupuesto`.`cuenta` (`id_cuenta`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;

CREATE INDEX `pk_cuenta_engreso` ON `db_presupuesto`.`egreso` (`id_cuenta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_presupuesto`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_presupuesto`.`ingreso` (
  `id_ingreso` INT NOT NULL AUTO_INCREMENT,
  `id_cuenta` INT NOT NULL,
  `saldo_ingreso` DOUBLE(6,2) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `estado_ingreso` ENUM('A', 'I') NOT NULL,
  PRIMARY KEY (`id_ingreso`),
  CONSTRAINT `pk_cuenta_ingreso`
    FOREIGN KEY (`id_cuenta`)
    REFERENCES `db_presupuesto`.`cuenta` (`id_cuenta`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;

CREATE INDEX `pk_cuenta_ingreso` ON `db_presupuesto`.`ingreso` (`id_cuenta` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
